#!/usr/bin/env python3
"""
DELIVERY130 — the Statistical Handbook.

Written for statisticians, not programmers. It contains no code. Every figure in
it is read out of delivery130/04_Datasets at generation time, so the handbook
cannot drift from the data it describes.

Its job is to let a reader at NBS answer, for any number in this submission:
what is it, where did it come from, what was assumed, who decided, and why.
"""
from __future__ import annotations
import csv, sys
from collections import defaultdict, Counter
from datetime import datetime, timezone
from pathlib import Path

BACKEND = Path(__file__).resolve().parents[1]; ROOT = BACKEND.parent
sys.path.insert(0, str(BACKEND))
from nmas.cohort import counts                                   # noqa: E402
from nmas.assumptions import REGISTER                            # noqa: E402
from nmas.fx import NGN_PER_USD_BY_YEAR, SUPERSEDED_FLAT_RATE    # noqa: E402

PKG = ROOT / "delivery130"; D = PKG / "04_Datasets"
OUT = PKG / "02_Methodology" / "NBS_Statistical_Handbook.md"
T = "=== PERIOD TOTAL ==="
csv.field_size_limit(10 ** 9)

def qkey(l): q, y = l.split("_"); return (int(y), int(q[1:]))
def f0(v):
    try: return float(v or 0)
    except (TypeError, ValueError): return 0.0
def usd(v): return "$%s" % format(v, ",.2f")
def ngn(v): return "₦%s" % format(v, ",.0f")

def main() -> int:
    c = counts()
    rows = [r for r in csv.DictReader((D / "Gross_Streaming_Revenue.csv").open(encoding="utf-8"))
            if r["artist_name"] != T]
    ex = [r for r in csv.DictReader((D / "Gross_Export_Revenue.csv").open(encoding="utf-8"))
          if r["artist_name"] != T]
    resid = list(csv.DictReader((D / "Artist_Residency_Classification.csv").open(encoding="utf-8")))
    plat = list(csv.DictReader((D / "Revenue_And_Cost_By_Platform.csv").open(encoding="utf-8")))
    dom = list(csv.DictReader((D / "Domestic_Production_Account.csv").open(encoding="utf-8")))
    gni = list(csv.DictReader((D / "GNI_Diaspora_Account.csv").open(encoding="utf-8")))
    periods = sorted({r["period"] for r in rows}, key=qkey)
    artists = sorted({r["artist_name"] for r in rows})

    gross_u = defaultdict(float); gross_n = defaultdict(float)
    for r in rows:
        gross_u[r["period"]] += f0(r["gross_streaming_revenue_usd"])
        gross_n[r["period"]] += f0(r["gross_streaming_revenue_ngn"])
    TOT_U = sum(gross_u.values()); TOT_N = sum(gross_n.values())
    Q3 = gross_u.get("Q3_2026", 0.0)

    pv = defaultdict(float)
    for p in plat: pv[p["platform"]] += f0(p["revenue_usd"])

    yt_src = Counter("observed" if (r.get("youtube_views_source") or "").startswith("observed")
                     else "none" if (r.get("youtube_views_source") or "").startswith("no YouTube")
                     else "estimated" for r in rows)
    months = Counter()
    for r in rows:
        b = r.get("spotify_listeners_basis") or ""
        months["3 months" if b.startswith("mean of 3") else
               "2 months" if b.startswith("mean of 2") else
               "1 month" if b.startswith("mean of 1") else "no monthly level"] += 1

    L = []; a = L.append
    a("# NBS Statistical Handbook")
    a("## Nigeria Music Analytics System — Delivery 130\n")
    a("Generated %s. Every figure below is read from `04_Datasets` when this document"
      % datetime.now(timezone.utc).strftime("%d %B %Y"))
    a("is produced, so it cannot disagree with the data it describes.\n")
    a("This handbook contains no programming content. It is written for statisticians.")
    a("Its purpose is that any number in this submission can be traced: what it is, where")
    a("it came from, what was assumed, and why that decision was taken.\n")
    a("---\n")

    a("## 1. What this submission measures\n")
    a("The estimated revenue earned by Nigerian recording artists from digital music")
    a("streaming platforms, quarter by quarter, from Q1 2019 to Q3 2026.\n")
    a("| | |")
    a("|---|---:|")
    a("| Artists | %d |" % len(artists))
    a("| Quarters | %d |" % len(periods))
    a("| Artist-quarter records | %s |" % format(len(rows), ","))
    a("| Gross streaming revenue, all quarters | %s |" % usd(TOT_U))
    a("| In naira, at each quarter's own rate | %s |" % ngn(TOT_N))
    a("| Of which Q3 2026 (INCOMPLETE quarter) | %s |" % usd(Q3))
    a("| Gross streaming revenue, 30 COMPLETE quarters | %s |" % usd(TOT_U - Q3))
    a("")
    a("### What it does not measure\n")
    a("This is important, and it is stated first rather than last.\n")
    a("- **It is not what platforms paid.** No platform reports payouts to this system.")
    a("  Revenue is estimated from audience figures using published per-unit rates.")
    a("- **It is not a count of streams.** No track-level stream count is available from")
    a("  any provider used here. Stream volumes are derived from audience counts.")
    a("- **It is not the whole Nigerian music industry.** It covers %d artists, digital" % len(artists))
    a("  streaming only. Live performance, physical sales, sync, publishing, radio")
    a("  royalties and merchandising are outside it entirely.")
    a("- **It is not value added until the deduction in section 9 is applied.** Revenue")
    a("  is output, not GDP.\n")
    a("---\n")

    a("## 2. The population, and why it is %d artists\n" % len(artists))
    a("The artists are those of the first submission to NBS. That list contains **%d rows**"
      % c["master_list_rows"])
    a("but describes **%d artists**, because %d pairs of rows are the same person recorded"
      % (c["distinct_artists"], len(c["duplicates"])))
    a("twice under two different provider identities:\n")
    a("| Kept | Merged into it | Why |")
    a("|---|---|---|")
    for d in c["duplicates"]:
        a("| %s | %s | One artist, two provider identities. Counting both inflates the "
          "artist count and charges the cost model for a person who does not exist. |"
          % (d["canonical"], d["alias"]))
    a("")
    a("**Decision:** count people, not records. A duplicate identity is merged into one")
    a("artist, and the observations of the identity with the fuller record are used.")
    a("**Reason:** an artist count is a count of economic units. Publishing a row count")
    a("under the word \"artists\" would overstate the population and every per-artist")
    a("figure derived from it.\n")
    a("---\n")

    a("## 3. Residence, and the split between GDP and GNI\n")
    a("> **NBS asked:** *\"Since the above-mentioned artists are living in those countries,")
    a("> their income will go to a different account which is not the production account.")
    a("> Kindly provide their revenue, cost of operation etc separate, it will be used to")
    a("> compile Gross National Income (GNI).\"*\n")
    a("This has been done. The classification is by **economic residence, not nationality**.")
    a("An artist of Nigerian heritage who lives and works abroad is not part of Nigerian")
    a("domestic production.\n")
    dom_n = sum(1 for r in resid if r["included_in_domestic_production"] == "Y")
    dia_n = sum(1 for r in resid if r["residence_classification"] == "diaspora_candidate")
    unk_n = sum(1 for r in resid if r["residence_classification"] == "unknown")
    a("| Classification | Artists | Gross revenue | Treatment |")
    a("|---|---:|---:|---|")
    a("| Resident in Nigeria | %d | %s | Domestic production account |"
      % (dom_n, usd(sum(f0(r["gross_revenue_usd"]) for r in resid if r["included_in_domestic_production"] == "Y"))))
    a("| Resident abroad, Nigerian heritage | %d | %s | Provided separately, for GNI compilation |"
      % (dia_n, usd(sum(f0(r["gross_revenue_usd"]) for r in resid if r["residence_classification"] == "diaspora_candidate"))))
    a("| Residence not established | %d | %s | **NBS adjudication required** |"
      % (unk_n, usd(sum(f0(r["gross_revenue_usd"]) for r in resid if r["residence_classification"] == "unknown"))))
    a("")
    a("**Files:** `Artist_Residency_Classification.csv` (one row per artist, with the")
    a("evidence for its classification), `Domestic_Production_Account.csv`,")
    a("`GNI_Diaspora_Account.csv`.\n")
    a("**A caution we place on the record.** The diaspora figures are supplied *for use in*")
    a("compiling GNI. They are not themselves GNI. What enters GNI is a specific income")
    a("flow under the national accounts residency rules; that determination is NBS's, and")
    a("this submission does not pre-empt it.\n")
    a("**Basis of the classification.** Residence is taken from the country the data")
    a("provider registers against the artist. That is a provider's administrative record,")
    a("not a residence determination. Every artist whose classification rests on it alone")
    a("is flagged `needs_nbs_adjudication = Y`. **%d of %d artists carry that flag.**"
      % (sum(1 for r in resid if r["needs_nbs_adjudication"] == "Y"), len(resid)))
    a("NBS should treat those as candidates to confirm, not as settled.\n")
    a("---\n")

    a("## 4. Revenue by product\n")
    a("> **NBS asked:** *\"Revenue generated and operating cost is broken-down according to")
    a("> product, example Spotify, Youtube, Deezer and others to enable us know the driver")
    a("> of digital music among them products.\"*\n")
    a("**File:** `Revenue_And_Cost_By_Platform.csv` — one row per platform, per quarter,")
    a("per account, with revenue, allocated cost and net result.\n")
    a("| Product | Gross revenue, all quarters | Share | What the figure rests on |")
    a("|---|---:|---:|---|")
    for name, _col, basis in [("Spotify", "", "Observed monthly listeners"),
                              ("YouTube", "", "Channel view volume"),
                              ("Deezer", "", "Observed fan counts"),
                              ("Other digital platforms", "", "**Nothing observed — an assumption**")]:
        v = pv.get(name, 0.0)
        a("| %s | %s | %.1f%% | %s |" % (name, usd(v), v / TOT_U * 100 if TOT_U else 0, basis))
    a("")
    a("**The driver of digital music revenue in this dataset is Spotify**, followed by")
    a("YouTube. Deezer is small. The fourth line is not a measurement and must not be read")
    a("as one: it is a flat uplift applied to Spotify revenue to stand for platforms that")
    a("were never queried (Apple Music, Amazon, Boomplay, Audiomack, Tidal). No figure from")
    a("any of those platforms appears anywhere in this submission.\n")
    a("---\n")

    a("## 5. How each revenue figure is calculated\n")
    a("### 5.1 Spotify — and the question NBS raised\n")
    a("> **NBS asked:** *\"Kindly give adequate explanation on what you mean by Spotify")
    a("> streams monthly listeners x 3.5 streams/listener/month x 3 months. Are you saying")
    a("> that the number of streams/listeners are constant?\"*\n")
    a("**The question was correct, and the method has been changed.**\n")
    a("The first submission took ONE listener figure for a quarter and multiplied it by")
    a("three months. That does assume the listener count is constant across the quarter.")
    a("It is not: it moves every month.\n")
    a("The quarter is now built from **each month's own observed listener level**:\n")
    a("> Quarterly streams = (Month 1 listeners × 3.5) + (Month 2 listeners × 3.5) +")
    a("> (Month 3 listeners × 3.5)\n")
    a("Equivalently, the mean of the observed monthly levels carried across three months.")
    a("Where all three months are observed the two are arithmetically identical.\n")
    a("**Coverage of that change, across all %s records:**\n" % format(len(rows), ","))
    a("| Monthly levels observed in the quarter | Records | Share |")
    a("|---|---:|---:|")
    for k in ("3 months", "2 months", "1 month", "no monthly level"):
        if months.get(k):
            a("| %s | %s | %.1f%% |" % (k, format(months[k], ","), months[k] / len(rows) * 100))
    a("")
    a("Every record states its own basis in the column `spotify_listeners_basis`.\n")
    a("**What remains an assumption.** The figure of **3.5 streams per listener per month**")
    a("is not measured by this system and is not reported by Spotify. It is an industry")
    a("proxy. Revenue scales linearly with it: if the true figure is 7, Spotify revenue")
    a("doubles. It is the single most consequential assumption in this submission, and NBS")
    a("may substitute its own value — the effect is proportional and easy to restate.\n")
    a("**What is measured.** The monthly listener counts themselves are observed from the")
    a("provider. What is assumed is how many times each listener plays a track.\n")
    a("### 5.2 YouTube\n")
    a("Revenue = quarterly view volume × $0.004 per view.\n")
    a("View volume is a *cumulative counter*: the platform reports total views to date, so")
    a("the quarter's volume is the increase across the quarter, not the level.\n")
    a("| Basis of the view volume | Records | Share |")
    a("|---|---:|---:|")
    a("| Observed increase in the counter | %s | %.1f%% |" % (format(yt_src["observed"], ","), yt_src["observed"] / len(rows) * 100))
    a("| Estimated (no usable observation) | %s | %.1f%% |" % (format(yt_src["estimated"], ","), yt_src["estimated"] / len(rows) * 100))
    a("| No YouTube presence found | %s | %.1f%% |" % (format(yt_src["none"], ","), yt_src["none"] / len(rows) * 100))
    a("")
    a("**Two decisions worth stating.**\n")
    a("*Counter restatements are removed.* A cumulative counter is sometimes restated by")
    a("the provider — channels merge, history is back-filled — and it leaps in one day by")
    a("more than the channel earns in years. One artist gained 826 million views on a")
    a("single day against a normal day of 351,682. Those are bookkeeping events, not")
    a("Nigerians watching videos, and counting them as revenue would be wrong. Any day")
    a("moving more than 50 times the artist's own typical daily rate is repriced at that")
    a("typical rate.\n")
    a("*A quarter must be spanned to be measured.* If the observations cover only part of")
    a("the quarter, the increase across them is not the quarter's volume. Where coverage")
    a("falls below 90%% the observation is treated as inadequate and an estimate is used")
    a("instead — and the record says so. Q3 2021 was measured over 8 days of 92 and")
    a("published a fall of 11.6%% that never happened.\n")
    a("### 5.3 Deezer\n")
    a("Revenue = fans × 2.0 streams per fan per month × 3 months × $0.004. Fan counts are")
    a("observed; the 2.0 is an assumption of the same kind as the Spotify 3.5.\n")
    a("### 5.4 Other digital platforms\n")
    a("A flat **30%% uplift on Spotify revenue**, standing for platforms never queried.")
    a("It is an assumption end to end and is carried in its own column, outside the")
    a("platform breakdown, so it cannot be mistaken for a measured platform.\n")
    a("---\n")

    a("## 6. Costs, and how they are attributed to products\n")
    a("> **NBS said:** *\"The break down is commendable.\"* — the four categories are kept")
    a("> unchanged.\n")
    a("| Category | Basis |")
    a("|---|---|")
    for x in REGISTER:
        if x.name.startswith("AVG_"):
            a("| %s | %s per artist per quarter (%s) |"
              % (x.name.replace("AVG_", "").replace("_COST_NGN", "").replace("_", " ").title(),
                 ngn(x.value), x.classification))
    a("")
    a("**On attributing cost to a product, we must be straightforward with NBS.**\n")
    a("NBS asked for operating cost broken down by product. It is provided, but with an")
    a("important qualification: **no cost in this dataset is directly attributable to a")
    a("platform.** The cost card is measured per artist per quarter — a studio session, a")
    a("distribution fee, a promotion budget — none of which arrives labelled with the")
    a("platform it served.\n")
    a("Every cost is therefore a **shared cost**, allocated to platforms **on each")
    a("platform's share of revenue in that quarter and account**. The allocation basis is")
    a("printed on every row of `Revenue_And_Cost_By_Platform.csv`, in the column")
    a("`cost_allocation_basis`, and the direct-cost column is zero throughout — because it")
    a("is genuinely zero, not because it was not computed.\n")
    a("**Why revenue share.** It is the conventional allocator where no usage measure")
    a("exists, and it is transparent. NBS may prefer another basis; the revenue shares are")
    a("published beside the allocation so any alternative can be applied.\n")
    a("**What the unit costs are.** They are assumptions drawn from secondary sources, not")
    a("observations of these artists' spending. Only the **artist counts** they are")
    a("multiplied by are measured.\n")
    a("---\n")

    a("## 7. Currency conversion\n")
    a("Every platform pays in US dollars. The naira figures are a **conversion**, not a")
    a("measurement, and the rate chosen decides the answer.\n")
    a("**A correction we must report.** The first submission applied a single flat rate of")
    a("₦%s per dollar to every quarter from 2019 to 2026. The naira did not sit still:"
      % format(SUPERSEDED_FLAT_RATE, ",.0f"))
    a("it moved from about ₦307 to about ₦1,530. Applying ₦1,500 to 2019 overstated the")
    a("2019 figure roughly fivefold.\n")
    a("**This matters more here than almost anywhere else**, because NBS is rebasing GDP")
    a("onto a **2019 base year**. A base-year figure inflated fivefold by a conversion rate")
    a("would carry through the whole rebased series.\n")
    a("| Year | Rate applied | 2019 comparison |")
    a("|---|---:|---|")
    for y in sorted(NGN_PER_USD_BY_YEAR):
        a("| %d | %.2f | %s |" % (y, NGN_PER_USD_BY_YEAR[y],
          "**the base year**" if y == 2019 else ""))
    a("")
    a("Rates are annual averages of the official rate, applied to each quarter of their")
    a("year. They are an **assumption**, held separately from the revenue logic precisely")
    a("so **NBS can replace them wholesale** with its own official series. Substituting a")
    a("different table changes only the naira columns; the dollar measurement is untouched.\n")
    a("Known simplifications: annual averages rather than quarterly, so within-year")
    a("movement is not captured; one rate for all flows, with no distinction between")
    a("official, NAFEM and parallel rates; and 2026 carries the 2025 rate because 2026 is")
    a("not a complete year. Each is a judgement NBS may wish to override.\n")
    a("---\n")

    a("## 8. The back-cast to 2019\n")
    a("> **NBS said:** *\"before the digital music data will be incorporated to GDP series,")
    a("> it has to be back casted down to 2019 new base year for it to align with the")
    a("> series otherwise it will give very high.\"*\n")
    a("The series runs from **Q1 2019**, the new base year, to Q3 2026 — %d quarters.\n" % len(periods))
    a("| Year | Gross revenue (USD) | Gross revenue (NGN, period rate) |")
    a("|---|---:|---:|")
    yu = defaultdict(float); yn = defaultdict(float)
    for p in periods:
        yu[int(p.split("_")[1])] += gross_u[p]; yn[int(p.split("_")[1])] += gross_n[p]
    for y in sorted(yu):
        a("| %d | %s | %s |" % (y, usd(yu[y]), ngn(yn[y])))
    a("")
    a("**How the early years were built.** The providers' own history does not reach back")
    a("uniformly to 2019. Where a series begins later than 2019, the earlier quarters are")
    a("estimated by a stated rule and every such record is labelled:\n")
    a("- **Spotify listeners** begin 2019-05-16. Q1 2019 levels are carried back from each")
    a("  artist's own first observed quarter, deflated by the growth the data itself shows")
    a("  between the first two observed quarters. Records carry")
    a("  `spotify_listeners_source = estimated`.")
    a("- **YouTube view history** begins 2021-09-23. For quarters before that, view volume")
    a("  is estimated from subscriber counts at a rate calibrated on the observed period")
    a("  and extrapolated backwards. Records carry `youtube_views_source = estimated`.\n")
    a("**This is the weakest part of the submission and we say so plainly.** No YouTube")
    a("view observation exists anywhere before September 2021, so YouTube revenue for")
    a("2019 to mid-2021 rests entirely on a model. It is labelled on every record, and a")
    a("reader can remove it by filtering on that column.\n")
    a("---\n")

    a("## 9. National accounts treatment\n")
    a("**Revenue is not value added, and this submission does not present it as such.**\n")
    a("**File:** `National_Accounts_Aggregates.csv`\n")
    a("| Concept | Treatment here |")
    a("|---|---|")
    a("| Output | Gross streaming revenue |")
    a("| Intermediate consumption | The four cost categories, all purchased services |")
    a("| Gross value added | Output less intermediate consumption |")
    a("| Compensation of employees | **NOT MEASURED.** The cost card has no labour component |")
    a("| Operating surplus / mixed income | The whole of value added, by consequence |")
    a("")
    a("**This treatment requires NBS confirmation.** Whether each cost category is")
    a("intermediate consumption under SNA, and whether any part of the artists' own return")
    a("is compensation of employees rather than mixed income, are national-accounts")
    a("judgements. We have set out the components so NBS can classify them; we have not")
    a("assumed the answer, and compensation of employees is left blank rather than zero")
    a("because it is unmeasured, not nil.\n")
    a("---\n")

    a("## 10. Every assumption, in one table\n")
    a("Nothing below is measured. Each is a number chosen for a stated reason, and each")
    a("can be replaced.\n")
    a("| Constant | Value | Class | What it does | Source | Limitation |")
    a("|---|---:|---|---|---|---|")
    for x in REGISTER:
        a("| %s | %s | %s | %s | %s | %s |"
          % (x.name, x.value, x.classification, x.meaning, x.source, x.limitation))
    a("")
    a("`EST` — estimated from observed data by a stated rule. `ASM` — assumed from a")
    a("source outside this system. Neither is an observation and neither is presented as")
    a("one.\n")
    a("---\n")

    a("## 11. How to read a value's status\n")
    a("Every value in this submission carries one of these:\n")
    a("| Code | Meaning |")
    a("|---|---|")
    a("| OBS | Observed directly from a provider |")
    a("| CNT | Counted from observed records |")
    a("| AGG | Aggregated from observations |")
    a("| EST | Estimated from observed data by a stated rule |")
    a("| ASM | Assumed from a source outside this system |")
    a("| UNK | **Not measured.** Never rendered as zero |")
    a("")
    a("**The distinction between UNK and zero is the most important convention in this")
    a("submission.** A blank means the quantity was not measured. A zero means it was")
    a("measured and found to be nil. They are never interchangeable. Where the")
    a("domestic/export split could not be measured — every quarter before Q1 2021 — the")
    a("cells are blank, not zero, because publishing zero would assert that Nigerian")
    a("artists earned nothing abroad in those years.\n")
    a("| Measure | Quarters measured | Quarters blank |")
    a("|---|---:|---:|")
    n_split = len({r["period"] for r in ex if r["gross_export_revenue_usd"] not in ("", None)})
    a("| Domestic / export split | %d | %d |" % (n_split, len(periods) - n_split))
    a("")
    a("---\n")

    a("## 12. Checks NBS can run\n")
    a("Every published figure can be recomputed from other published columns. These hold")
    a("on all %s records and can be tested in a spreadsheet:\n" % format(len(rows), ","))
    a("| Check | Identity |")
    a("|---|---|")
    a("| Spotify revenue | listeners × 3.5 × 3 × 0.004 |")
    a("| YouTube revenue | views × 0.004 |")
    a("| Deezer revenue | fans × 2.0 × 3 × 0.004 |")
    a("| Other platforms | Spotify revenue × 0.30 |")
    a("| Gross revenue | the four above, summed |")
    a("| Naira | gross revenue × that quarter's rate |")
    a("| Quarter total | the sum of that quarter's artist records |")
    a("| Account split | domestic + diaspora + unclassified = total |")
    a("")
    a("**One warning.** `Gross_Streaming_Revenue.csv` and `Gross_Export_Revenue.csv` each")
    a("contain a `=== PERIOD TOTAL ===` row per quarter, reproduced because the first")
    a("submission carried them. **Exclude those rows when summing.** Including them")
    a("doubles every total exactly.\n")
    a("---\n")

    a("## 13. What changed since the first submission, and why\n")
    a("| Change | Reason |")
    a("|---|---|")
    a("| Series extended to 31 quarters from Q1 2019 | NBS requires the 2019 base year |")
    a("| Naira converted at each year's own rate | A flat ₦1,500 overstated 2019 by ~5× |")
    a("| Spotify built from each month's own level | NBS asked whether listeners were constant. They were being treated as constant |")
    a("| Diaspora artists separated | NBS requires them outside the production account |")
    a("| Revenue and cost broken down by platform | NBS asked, to identify the driver |")
    a("| Output, intermediate consumption and GVA separated | Revenue is not value added |")
    a("| Two duplicate artists merged | One person counted twice inflates the population and the cost model |")
    a("| Export markets computed per artist | The first submission wrote one identical market list on every row; it was not a detection |")
    a("| Provider counter restatements removed | A single day of 826 million views is a bookkeeping event, not consumption |")
    a("| Every record states its own basis | So an estimate can never be read as an observation |")
    a("")
    a("---\n")

    a("## 14. Limitations, stated plainly\n")
    a("1. **No platform payout is observed.** All revenue is estimated from audience.")
    a("2. **No track-level stream count exists** in any source used here.")
    a("3. **The 3.5 and 2.0 multipliers are proxies.** Revenue scales linearly with them.")
    a("4. **The 30%% other-platform uplift measures nothing.** No such platform was queried.")
    a("5. **YouTube before September 2021 is entirely modelled.** No view observation exists.")
    a("6. **Residence rests on a provider's administrative country field** for most artists.")
    a("7. **Exchange rates are annual averages** of one rate, not quarterly and not")
    a("   differentiated by market.")
    a("8. **Q3 2026 is incomplete** — observations end 11 August 2026, 42 of 92 days — yet")
    a("   its level-based components bill three full months. It is %.2f%% of the headline."
      % (Q3 / TOT_U * 100))
    a("   The 30-complete-quarter total is published beside it for this reason.")
    a("9. **Employment is national**, from secondary sources. It is not these artists'")
    a("   employees and is not scaled to them.\n")
    a("---\n")

    a("## 15. Authorship\n")
    a("**Authorship and attribution remain subject to NBS review and approval, following")
    a("completion of the full back-cast dataset and presentation to the Statistician")
    a("General of the Federation.** Nothing in this submission should be read as claiming")
    a("that authorship has been settled.\n")
    a("---\n")

    a("## 16. Glossary\n")
    a("| Term | Meaning in this submission |")
    a("|---|---|")
    a("| Monthly listeners | Distinct accounts that played an artist in the preceding 30 days, as reported by the platform. A *level*, not a count of plays |")
    a("| Stream | One play of a track. Not observed here; derived from listeners |")
    a("| Channel views | Cumulative total views of an artist's YouTube channel. The quarter's volume is the increase across the quarter |")
    a("| Subscribers / fans | Standing followers of a channel or profile. A level |")
    a("| Gross streaming revenue | Estimated artist-side revenue before any cost |")
    a("| Domestic / export split | The share of listening inside and outside Nigeria, from observed listener geography |")
    a("| Back-cast | A figure for a period earlier than the provider's own history, produced by a stated rule |")
    a("| Economic residence | Where an artist lives and works. Distinct from nationality |")
    a("| Period total row | A summary row inside the data file. Exclude when summing |")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L), encoding="utf-8")
    print("wrote %s  (%d lines, %.0f KB)" % (OUT.relative_to(ROOT), len(L), OUT.stat().st_size / 1024))
    print("  covers: %d artists, %d quarters, %s, %d sections" % (len(artists), len(periods), usd(TOT_U), 16))
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
